### ISSUE TITLE
☂️ Null Safety Migration Issue Umbrella thread

### ISSUE THREAD

**Issue by singularity-s0** [DanXi-Dev/DanXi#101]
- [x] Can't export image in BBS
- [x] Can't load dev announcement
- [x] Can't load exam
- [x] Can't display correct error message in BBS
`type 'Null' is not a subtype of type 'FutureOr<List<BBSPost>>'`
- [x] https://github.com/aaassseee/screen_brightness/issues/2
- [x] Can't display eCard QR Code
