### ISSUE TITLE
1.3.11 Milestone

### ISSUE THREAD

**Issue by w568w** [DanXi-Dev/DanXi#174]
This issue is a collection covering our plans before 1.3.11 version becomes available.

- [x] Revert tab order
- [x] #148
- [x] #179
- [x] #189
- [x] Attempt to cope with item locating issues
- [x] Remove Fudan Daily (from projects and descriptions)
- [x] #196

**Comment by w568w** [comment]
@Boreas618 What about item locating issues? If you believe that it is fixed (or there is no better solution), you can tick it off.

**Comment by Boreas618** [comment]
I'm trying to address the locating issues in the coming days.
