### ISSUE TITLE
To-do before first release

### ISSUE THREAD

**Issue by kavinzhao** [DanXi-Dev/DanXi#30]
- [x] 完成发帖编辑器和tag编辑器
- [x] 上线搜索和电梯直达等web端已有的功能
- [ ] 将hardcode的`开学日期`更换为动态获取
- [x] 更新为新的图标
- [x] 完成翻页功能
- [x] 解决`不能双击回顶部`和`不能拖动scrollBar`的问题
- [x] 解决iOS启动时刷新的问题；使Storyboard兼容Dark Mode
- [x] 课程表导入系统日历时，应请求系统直接打开生成的ics，而非显示分享页面
- [x] 解决课程表每次翻页都要闪一下“加载中”的bug
- [x] 支持Quote回帖

**Comment by w568w** [comment]
> 课程表导入系统日历时，应请求系统直接打开生成的 ics，而非显示分享页面

Android 很少直接请求打开文件的 Intent （即采用 `ACTION_VIEW`）（图片除外）。  
如： Android 版的 Github 应用就直接对下载后的 Release 文件使用打开文件请求，这在大多数国内 ROM 上是低效的，因为打开选项里通常只有「使用系统浏览器打开」「使用 QQ 浏览器快速浏览」「使用 QQ/微信 分享」和「使用手机淘宝搜索」。  
惯常的做法是使用`ACTION_SHARE`分享，然后保存到某个地方，再使用其他文件管理类应用（包括QQ等）打开。  
此外，如果用户需要将文件保存以便发送到他的其他设备，使用分享方式也比较方便一些。  

不清楚 iOS 的打开文件方式实现。

**Comment by kavinzhao** [comment]
> > 课程表导入系统日历时，应请求系统直接打开生成的 ics，而非显示分享页面
> 
> 
> 
> Android 很少直接请求打开文件的 Intent （即采用 `ACTION_VIEW`）（图片除外）。  
> 
> 如： Android 版的 Github 应用就直接对下载后的 Release 文件使用打开文件请求，这在大多数国内 ROM 上是低效的，因为打开选项里通常只有「使用系统浏览器打开」「使用 QQ 浏览器快速浏览」「使用 QQ/微信 分享」和「使用手机淘宝搜索」。  
> 
> 惯常的做法是使用`ACTION_SEND`分享，然后保存到某个地方，再使用其他文件管理类应用（包括QQ等）打开。  
> 
> 此外，如果用户需要将文件保存以便发送到他的其他设备，使用分享方式也比较方便一些。  
> 
> 
> 
> 不清楚 iOS 的打开文件方式实现。

但目前很多用户在使用过程中都不知道如何导入系统日历；要求用户先保存再打开不太合理，能否让app直接像文件管理类应用那样打开？
